[tool.ruff]
line-length = 100
select = ["E", "F", "W", "I", "N", "D", "UP", "ANN", "C90"]
ignore = []
exclude = [".venv", "venv", "build", "dist", "__pycache__"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"] 